import { Lock, Search, Plus, Settings, Copy, Eye, EyeOff, Trash2, LogOut, RefreshCw, Key, CreditCard, User, FileText, ChevronRight, Tag, Link, Download, Cloud, LayoutGrid, Shield, Star, Smartphone, QrCode, ArrowLeft, FolderPlus, HardDriveDownload } from "lucide-react"

export const Icons = {
  lock: Lock,
  search: Search,
  plus: Plus,
  settings: Settings,
  copy: Copy,
  eye: Eye,
  eyeOff: EyeOff,
  trash: Trash2,
  logout: LogOut,
  refresh: RefreshCw,
  key: Key,
  card: CreditCard,
  user: User,
  note: FileText,
  chevronRight: ChevronRight,
  tag: Tag,
  link: Link,
  download: Download,
  cloud: Cloud,
  layoutGrid: LayoutGrid,
  shield: Shield,
  star: Star,
  smartphone: Smartphone,
  qrCode: QrCode,
  arrowLeft: ArrowLeft,
  folderPlus: FolderPlus,
  cloudDownload: HardDriveDownload
}